### ISSUE TITLE
Claiming Rewards: Missing posting authority

### ISSUE THREAD

**Issue by cardboard-git** [pharesim/hive-python#1]
When using claim_reward_balance method, api returns an error:
Unexpected exception! Please report at https://github.com/pharesim/hive-python/issues -- RPCError: tx_missing_posting_auth from api.hive.blog (missing required posting authority:Missing Posting Authority cardboard) in verify_authority
failing on tx_missing_posting_auth from api.hive.blog (missing required posting authority:Missing Posting Authority cardboard) in verify_authority

**Comment by pharesim** [comment]
Why didn't I see this before? Also, works for me, that call is used daily with curangel.
